# -*- coding: utf-8 -*-
"""new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekydHPF8oBcvIBDcG7l-bjUC2VlCB_Hj

**sklearn**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Advertising.csv")

df.info()

df.describe()

df.head()

df.drop("Unnamed: 0",axis=1,inplace=True)

df.head()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

x=df.iloc[:,:3]
y=df.iloc[:,-1]

x.shape

y.shape

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

x_train.shape

lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

print("m:",lr.coef_)
print("b:",lr.intercept_)

from sklearn.metrics import r2_score
print("r2_score:",r2_score(y_test,y_pred))

"""**OLS**"""

class OLS:
  def __init__(self):
    self.b=None
    self.m=None
  def fit(self , x_train,y_train):
    x_train=np.insert(x_train,0,1,axis=1)
    betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
    self.b=betas[0]
    self.m=betas[1:]
    print("m:",self.m,"b:",self.b)
  def predict(self,x_test):
    y_pred=np.dot(x_test,self.m)+self.b
    return y_pred

ols=OLS()

ols.fit(x_train,y_train)

from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
y_pred=ols.predict(x_test)

print("r2_score:",r2_score(y_test,y_pred))
print("mse:",mean_squared_error(y_test,y_pred))
print("mae:",mean_absolute_error(y_test,y_pred))
r2_ols=r2_score(y_test,y_pred)

"""**Batch Gradient Descent**"""

x_train = np.array(x_train)
y_train = np.array(y_train)

class BatchGD:
  def __init__(self,epochs,learning_rate):
    self.m=None
    self.b=None
    self.epochs=epochs
    self.l_r=learning_rate

  def fit(self,x_train,y_train):



    self.m=np.ones(x_train.shape[1])
    self.b=0
    for i in range(self.epochs):

      y_hat=np.dot(x_train,self.m)+self.b
      m_der=-2*np.dot(x_train.T,(y_train - y_hat)) / x_train.shape[0]
      self.m=self.m-(self.l_r*m_der)
      b_der=-2*np.mean(y_train-y_hat)
      self.b=self.b-(self.l_r * b_der)


    print("m:",self.m,"b:",self.b)

  def predict(self,x_test):
    return np.dot(x_test,self.m)+self.b



batch=BatchGD(epochs=10000,learning_rate=0.001)

batch.fit(x_train,y_train)
y_pred=batch.predict(x_test)
r2_batch=r2_score(y_test,y_pred)
print("r2_score:",r2_score(y_test,y_pred))
print("mse:",mean_squared_error(y_test,y_pred))
print("mae:",mean_absolute_error(y_test,y_pred))

"""**SOCHASTIC GRADIENT DESCENT**"""

class StochasticGD:
 def __init__(self,epochs,learning_rate):
   self.m=None
   self.b=None
   self.epochs=epochs
   self.l=learning_rate

 def fit(self,x_train,y_train):
   self.b=0
   self.m=np.ones(x_train.shape[1])

   for i in range(self.epochs):
     for j in range(x_train.shape[0]):
       indx=np.random.randint(0,x_train.shape[0])
       y_hat=np.dot(x_train[indx],self.m)+self.b
       m_der=-2*np.dot((y_train[indx]-y_hat),x_train[indx])
       self.m=self.m-(self.l*m_der)
       b_der=-2*(y_train[indx]-y_hat)
       self.b=self.b-(self.l*b_der)

   print(self.m,self.b)
 def predict(self,x_test) :
   return   np.dot(x_test,self.m)+self.b

scd = StochasticGD(15, 0.001)

scd.fit(x_train, y_train)

y_pred = scd.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("mse:",mean_squared_error(y_test,y_pred))
print("mae:",mean_absolute_error(y_test,y_pred))
r2_sgd=r2_score(y_test, y_pred)

plt.scatter(y_test,y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

"""MINI BATCH GRADIENT DESCENT

"""

class miniBatchGD:
  def __init__(self,batch_size,epochs,learning_rate):
    self.m=None
    self.b=None
    self.batch_size=batch_size
    self.epochs=epochs
    self.lr=learning_rate
  def fit(self,x_train,y_train):
    self.b=0
    self.m=np.ones(x_train.shape[1])
    for i in range(self.epochs):
      for j in range(int(x_train.shape[0]/self.batch_size)):
        indx=np.random.choice(x_train.shape[0],self.batch_size,replace=False)
        y_hat=np.dot(x_train[indx],self.m)+self.b
        b_=-2*np.mean(y_train[indx]-y_hat)
        m=-2*np.dot((y_train[indx]-y_hat),x_train[indx])
        self.b=self.b-(self.lr*b_)
        self.m=self.m-(self.lr*m)

    print(self.m,self.b)
  def predict(self,x_test):
    return np.dot(x_test,self.m)+self.b

mini=miniBatchGD(batch_size=int(x_train.shape[0]/50),learning_rate=0.001,epochs=100)
mini.fit(x_train,y_train)
y_pred=mini.predict(x_test)
print("r2_score:",r2_score(y_test,y_pred))
r2_mini=r2_score(y_test,y_pred)
print("mse:",mean_squared_error(y_test,y_pred))
print("mae:",mean_absolute_error(y_test,y_pred))

methods=["OLS","Batch GD","SGD","Mini Batch"]
scores=[r2_ols,r2_batch,r2_sgd,r2_mini]

plt.bar(methods,scores)
plt.ylabel("R2 Score")
plt.title("Model Comparison")
plt.show()

